---
- hosts: localhost
  become: yes
  pre_tasks:
   - name: Make sure all the servers are pingable
     ping:
  tasks:
    - name: Stop the service #Change services according to the requirement
      service:
        name: "{{ item }}"
        state: stopped
      loop:
         - httpd
         - sshd
    - name: Clean yum cache 
      file:
        path: /var/cache/yum/
        state: absent 
 
    - name: Check space in /var [Abort the playbook if there is no sufficient space]
      shell: df -h /var
      register: space
    - debug: var=space
      tags: space

    - name: Pause for 2 minutes
      pause:
        minutes: 2

    - name: Patch the servers
      shell: yum -y update
    
    - name: Clean yum cache 
      file:
        path: /var/cache/yum/
        state: absent

    - name: Reboot servers
      shell: sleep 2 && /sbin/shutdown -r now 
      async: 1
      poll: 0
      tags: boot

    - name: Wait for 2 minutes for server to come up after rebooting
      pause:
        minutes: 2

    - name: Confirm if server is responding to ssh
      wait_for:
        host: localhost
        port: 22
        delay: 15
        timeout: 300
        state: started

    - name: Clean yum cache
      file:
        path: /var/cache/yum/
        state: absent

    - name: Start the services #Change services according to the requirement
      service:
        name: "{{ item }}"
        state: started
      loop:
         - httpd
         - sshd

#   - name: Check if the service is up 
#     shell: ps -ef | grep "service-name"
#     register: service
#   - debug: var=service 
