- hosts: localhost
  connection: local
  vars:
    username: Swati Kalia
    roleassignmentname: Application administrator
    scope: /subscriptions/6530cd7d-1f02-4bac-80bd-55ac743cdf4d
  
  tasks: 
  - name: Get role assignments for specific service principal
    azure_rm_roleassignment_info:
      name: "{{ roleassignmentname }}"
      scope: "{{ scope }}"
    register: output

  - name: Print the value of output
    debug: 
      var: output
