---
- name: Create resource_group , VPC and Subnet
  hosts: localhost
  connection: local
  vars:
    resource_group: index
    vnet_name: VNet-Index
    subnet_name: Testsubnet
    location: eastus2

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}" 
        location: "{{ location }}"

    - name: Create first virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ vnet_name }}"
